export const three60Env = {
	LOGIN_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL_LOGIN || "",
	REGISTER_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL_REGISTER || "",
	TODOS_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL_TODOS || "",
	CLIENT_ID: process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID || "",
	DOMAIN: process.env.NEXT_PUBLIC_AUTH0_DOMAIN || "",
};
